If session expired, reconnected with auth token
longportapp/openapi-protocol pull request #1
Opened 2022-06-21 09:35 UTC by Patrick0308

Add AuthTokenGetter on DialOptions. If session expired, reconnected with auth token.

2022-06-22 07:47 UTC, sunfuze requested changes

2022-06-22 07:47 UTC, sunfuze commented on go/client/client.go
> +		return nil
如果不存在的话应该报错吧

2022-06-22 07:47 UTC, sunfuze commented on go/client/client.go
> +func (c *Client) reconnectDial() error {
这里要加个错误判读，如果是 session 过期的错误需要 走 auth 的流程

2022-06-22 07:48 UTC, Patrick0308 commented on go/client/client.go
> +		return nil
我看之前client的设计，是可以没有auth流程的

2022-06-22 07:50 UTC, Patrick0308 commented on go/client/client.go
> +func (c *Client) reconnectDial() error {
c.isAuthExpired() 判断了 serssion 是否过期

2022-06-22 07:55 UTC, sunfuze commented on go/client/client.go
> +		return nil
协议是这样的，不要求服务端一定要有 auth

2022-06-22 07:55 UTC, sunfuze commented on go/client/client.go
> +		return nil
那不改也没事，是你 sdk 这边在用，sdk 有给就行了

2022-06-22 07:57 UTC, sunfuze commented on go/client/client.go
> +func (c *Client) reconnectDial() error {
这个是客户端按照 session 过期时间判断，服务端是有可能返回 session 过期的错误的，这时候还是要走 auth 获取 otp 校验的流程

2022-06-22 08:01 UTC, Patrick0308 commented on go/client/client.go
> +func (c *Client) reconnectDial() error {
ok，那我加一下

2022-06-23 03:34 UTC, sunfuze commented on go/client/client.go
> +	if res.CMD() == uint32(protocol.StatusUnauthenticated) {
应该不是 cmd 方法吧

2022-06-23 04:26 UTC, merged